# Generated by Django 2.0 on 2018-07-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='mods',
            field=models.IntegerField(blank=True, db_column='Mod_id', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.CharField(blank=True, max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='lastconnect',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='totalconnect',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
