
def fr():
    lang = {}

    lang["langue.langue_flag_en"] = "{% static 'dotrack/img/logo.png' %}"
    lang["langue.langue_flag_fr"] = "{% static 'dotrack/img/logo.png' %}"
    lang["form_menu_acceuil"] = "Acceuil"
    lang["form_menu_apropos"] = "Apropos"
    lang["form_menu_contact"] = "Contact"
    lang["form_menu_courrier"] = "Courrier"
    lang["form_menu_connexion"] = "Connexion"
    lang["form_bienvenue_sur_dotrack"] = "Bienvenue sur Document Tracking"
    lang["form_voir_demo"] = "Voire la démo"
    lang["form_password"] = "Mot de passe"
    lang["form_email"] = "Adresse Email"
    lang["form_statyTune"] = "Garder ma session ouverte pour restez Informer"
    lang["form_forgot_text"] = "Mot de Passe Oublié"
    lang["form_menu_inscription"] = "Inscription"
    lang["form_nom"] = "Nom"
    lang["form_facilite"] = "Facilté"
    lang["form_rapidite"] = "Rapidité"
    lang["form_qualite"] = "Qualité"
    lang["form_dashboard"] = "Tableau de Board"
    lang["form_logout"] = "Deconnexion"
    lang["form_profile"] = "Profile"
    lang["form_utilisateurs"] = "Utilisateurs"
    lang["form_nouvelle"] = "Nouvel (le)"
    lang["form_consulter"] = "Voir tous"
    lang["form_Statistiques"] = "Statistiques"
    lang["form_Entreprises"] = "Entreprises"
    lang["form_Documents"] = "Documents"
    lang["form_reglages"] = "Reglages"
    lang["form_courrier_box"] = "Boite courrier"
    lang["form_archives"] = "Archives"
    lang["form_messages"] = "Messages"
    lang["form_outils"] = "Outils"
    lang["form_dashbooard_admin_texte1"] = "Merci d'utiliser DOTrack votre application de gestion et de traitement de vos Documents. Aucune mise à jour n'est disponible pour l'instant !. Pour toutes Questtion ou suggestion sur les fonctionnalités du système bien vouloir contacter l'équipe"
    lang["form_dashbooard_admin_texte2"] = "Toute action de modification ou de suppression a ce niveau modifira les donnees de toute votre entreprise ! il vous est recommandé de bien vérifier toutes vos actions."
    lang["form_alert_securite"] = "Alerte de Securité"
    lang["form_welcome"] = "Bienvenue"
    lang["form_Choisir_une_entreprise"] = "Choisir entreprise"
    lang["form_Entreprise_Ajoute_avec_succes"] = "Entreprise Ajouté avec succes"
    lang["form_Enregistrer"] = "Enregistrer"
    lang["form_Veuillez_ChoisiruneEntreprise"] = "Choisir une Entreprise"
    lang["form_site_web"] = "Site Web"
    lang["form_changer_logo"] = "Changer le Logo"
    lang["form_choisir_photo"] = "Choisir une Image"
    lang["form_phone"] = "Numero Telephone"
    lang["form_ville"] = "Ville"
    lang["form_pays"] = "Pays"
    lang["form_champ_obligatoire"] = "Tous les Champs sont Obligatoire"
    lang["form_Cicursale"] = "Succursale"
    lang["form_Sucursale_Ajoute_avec_succes"] = "Sucursale Ajouté avec succes"
    lang["form_prenom"] = "Prenom"
    lang["form_user"] = "Type Utilisateur"
    lang["form_type_users"] = "Type d'Utilisateur"
    lang["form_abbreviation"] = "abbreviation"
    lang["form_typeUser_Ajoute_avec_succes"] = "Type Utilisateur ajoute avec succes"
    lang["form_fonction"] = "fonction"
    lang["form_admin"] = "Administrateur"
    lang["form_Chat"] = "Discussion"
    lang["form_Latest_Members"] = "Recents Membres"
    lang["form_NewMembers"] = "Nouveaux Membres"
    lang["form_ajouter"] = "Ajouter"
    lang["form_Members"] = "Membres"
    lang["form_accederaunecicursale"] = "Veuillez Acceder a une Sucursale"
    lang["form_DroitDacces"] = "Droit D'acces"
    lang["form_acceuil_rapiditeText"] = "DOTrack vous permet de rester en connexion permanente avec les membres de votre equipe et d'echanger instentanement"
    lang["form_acceuil_faciliteText"] = "Evitez les tracasseries des archives,...Faites des recherches rapides, des rangements structures, des traitements en groupe"
    lang["form_acceuil_qualiteText"] = "Administrez toutes vos entreprises de facon separe et via un seul compte; configurez vos sms, vos mails, vos taches, vos annonces..."
    lang["form_acceuil_Texttitre1"] = "Assurez la Getion et le Traitement de vos Documents de facon Simple et efficace"
    lang["form_slogan"] = "Slogan"
    lang["form_siteweb"] = "Site Web"
    lang["form_Details"] = "Details"
    lang["form_delete_message"] = "Êtes-vous sûr de vouloir supprimer ceci ?"
    lang["form_veuillezchoisir_action"] = "Veuillez choisir aumoins une action a votre gauche"
    lang["form_erreur"] = "Erreur"
    lang["form_entreprise_supprimer"] = "Votre element entreprise à été supprimer avec succes"
    lang["form_aucunedonne"] = "Aucune donnee trouve !"
    lang["form_aucunedonne_text"] = "Aucun utilisateur trouver / Ajoutez en via le formulaire d'ajout."
    lang["form_lastConnexion"] = "Derniere Connexion"
    lang["form_lastDeconnexion"] = "Derniere Deconnexion"
    lang["form_Totalconnexion"] = "Nombre de Connexion"
    lang["form_controlActivity"] = "Controller l'activité"
    lang["form_aboutme"] = "Apropos de Moi"
    lang["form_description"] = "Description"
    lang["form_location"] = "Localisation"
    lang["form_DroitDacces_menus"] = "Droits D'acces Menus"
    lang["form_Modifier_mes_informations"] = "Modifier mes informations"
    lang["form_Dossiers"] = "Dossiers"
    lang['form_libeller'] = "Libeller"
    lang["form_abbr"] = "Abreviation"
    lang["form_dossier_ajouter_succes"] = "Votre dossier a ete ajoute avec succes"
    lang['formatFichier'] = "Format des Fichiers"
    lang['typeCourriers'] = "Types de Courriers"
    lang['typeArchives'] = "Types D'archives"
    lang['form_User_Ajoute_avec_succes'] =  "Utilisateur ajouter avec succes a la liste"
    lang['form_mouchard'] = "Mouchard"
    lang['form_activiteRecente'] = "Activités Recentes"
    lang['form_search'] = "Rechercher"
    lang['mouchard'] = "Mouchard"
    lang['form_choisir_fichier'] = "Choisir un Fichier"

    return lang


def en():
    lang = {}
    
    lang['form_choisir_fichier'] = "Choose a File"
    lang['mouchard'] = "Mouchard"
    lang['form_search'] = "Search"
    lang['form_activiteRecente'] = "Recents Activity"
    lang['form_mouchard'] = "Mouchard"
    lang['form_User_Ajoute_avec_succes'] =  "Users are succefull add to the list"
    lang['typeArchives'] = "Types D'archives"
    lang['typeCourriers'] = "Types de Courriers"
    lang['formatFichier'] = "File Format"
    lang["form_dossier_ajouter_succes"] = "The folder are saved with success"
    lang["form_abbr"] = "Abreviation"
    lang['form_libeller'] = "Title"
    lang["form_Dossiers"] = "Folders"
    lang["form_Modifier_mes_informations"] = "Edit my Account Informations"
    lang["form_DroitDacces_menus"] = "Permission to access"
    lang["form_location"] = "Location"
    lang["form_description"] = "Description"
    lang["form_aboutme"] = "About Me"
    lang["form_controlActivity"] = "Check Activity"
    lang["form_Totalconnexion"] = "Number of Connexion"
    lang["form_lastDeconnexion"] = "Last Deconnexion"
    lang["form_lastConnexion"] = "Last Connexion"
    lang["form_aucunedonne_text"] = "No users found / add it using the add form"
    lang["form_aucunedonne"] = "No data found !"
    lang["form_entreprise_supprimer"] = "Your business element has been successfully deleted"
    lang["form_erreur"] = "Error"
    lang["form_veuillezchoisir_action"] = "Please choose at least one action on your left"
    lang["form_delete_message"] = "Are you sure you want to delete this ?"
    lang["form_slogan"] = "Slogan"
    lang["form_siteweb"] = "Website"
    lang["form_Details"] = "Details"
    lang["form_acceuil_Texttitre1"] = ""
    lang["form_acceuil_qualiteText"] = ""
    lang["form_acceuil_faciliteText"] = "D"
    lang["form_acceuil_rapiditeText"] = "DOTrack"
    lang["form_DroitDacces"] = "Permission to access"
    lang["form_accederaunecicursale"] = "Please Access a Sucursale"
    lang["form_Members"] = "Members"
    lang["form_ajouter"] = "Add"
    lang["form_NewMembers"] = "New Members"
    lang["form_Latest_Members"] = "Latest Members"
    lang["form_Chat"] = "Chat"
    lang["form_admin"] = "Administrator"
    lang["form_fonction"] = "function"
    lang["form_typeUser_Ajoute_avec_succes"] = "User type are successfull adds"
    lang["form_abbreviation"] = "abbreviation"
    lang["form_type_users"] = "Users Types"
    lang["form_user"] = "User Type"
    lang["form_prenom"] = "Surname"
    lang["form_Sucursale_Ajoute_avec_succes"] = "Branch was succesfully added"
    lang["form_Cicursale"] = "Branch"
    lang["form_champ_obligatoire"] = "All fields are mandatory"
    lang["form_pays"] = "Country"
    lang["form_ville"] = "City"
    lang["form_phone"] = "Phone Number"
    lang["form_choisir_photo"] = "Choose a Picture"
    lang["form_changer_logo"] = "Change Profile Picture"
    lang["form_site_web"] = "Web Site"
    lang["form_Veuillez_ChoisiruneEntreprise"] = "Choose a Compagny"
    lang["form_Enregistrer"] = "Save"
    lang["form_Entreprise_Ajoute_avec_succes"] = "Compagny was succesfully added"
    lang["form_Choisir_une_entreprise"] = "Choose a company"
    lang["form_welcome"] = "Welcome"
    lang["form_alert_securite"] = "Security Alert"
    lang["form_dashbooard_admin_texte2"] = "Any modification or deletion action at this level will change the data of your entire company! it is recommended that you check all your actions."
    lang["form_dashbooard_admin_texte1"] = "Thank you for using DOTrack your application for managing and processing your Documents. No update is available at this time! For all Questtion or suggestion on the features of the system please contact the team"
    lang["form_outils"] = "Tools"
    lang["form_messages"] = "Messages"
    lang["form_archives"] = "Archives"
    lang["form_courrier_box"] = "Mail box"
    lang["form_reglages"] = "Settings"
    lang["form_Documents"] = "Documents"
    lang["form_Entreprises"] = "Company"
    lang["form_Statistiques"] = "Statistics"
    lang["form_consulter"] = "View all"
    lang["form_nouvelle"] = "New"
    lang["form_utilisateurs"] = "Users"
    lang["form_profile"] = "Profile"
    lang["form_logout"] = "Sign Out"
    lang["form_dashboard"] = "Dashboard"
    lang["langue.langue_flag_en"] = "{% static 'dotrack/img/logo.png' %}"
    lang["langue.langue_flag_fr"] = "{% static 'dotrack/img/logo.png' %}"
    lang["form_qualite"] = "Quality"
    lang["form_rapidite"] = "Rapidity"
    lang["form_facilite"] = "Facility"
    lang["form_nom"] = "Name"
    lang["form_menu_inscription"] = "SignUp"
    lang["form_menu_acceuil"] = "Home"
    lang["form_menu_apropos"] = "About"
    lang["form_menu_contact"] = "Contact us"
    lang["form_menu_courrier"] = "Mails"
    lang["form_menu_connexion"] = "LogIn"
    lang["form_bienvenue_sur_dotrack"] = "Welcome to Document Tracking"
    lang["form_voir_demo"] = "View the demo"
    lang["form_password"] = "Password"
    lang["form_email"] = "Email Adress"
    lang["form_statyTune"] = "Keep my session open"
    lang["form_forgot_text"] = "I just forget my password"

    return lang


def loadLang(file):
    if(file == "en"):
        lg = en()
    else:
        lg = fr()
    return lg


def checkLangAbbr(abbr):
    if(abbr != "en" and abbr != "fr"):
        return "fr"
    else:
        return abbr


def defaultLang():
    return "fr"
